print('Hello, World!')
print('Everybody loves python because it is very easy to learn')
print('The sum of 1 and 2 is ', 1 + 2)
print('The difference of 2 and 1 is ', 2 - 1)
print('The product of 2 and 3 is ', 2 * 3)
print('The division of 3 and 2 is ', 3 / 2)
print('The remainder of 3 divided by 2 is', 3 % 2)
print('The remainder of 9 divided by 5 is', 9 % 5)
print('The floor division of 3 by 2 is ', 3 // 2)
print('The exponential of 2 of 3 is ', 2 ** 3)

